# Generated by Django 4.2.7 on 2024-02-14 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='action',
            name='action_acti_done_ti_7105d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='action',
            name='action_acti_target__e4f2ef_idx',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='done_time',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='action',
            name='target_content_type',
        ),
        migrations.AddField(
            model_name='action',
            name='target_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_obj', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['-created'], name='action_acti_created_4364ca_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['target_ct', 'target_id'], name='action_acti_target__8cf40b_idx'),
        ),
    ]
